// This file is generated by the 'node-soap-servicegenerator'
// visit : https://github.com/BreeeZe/node-soap-servicegenerator for more info

var NOT_IMPLEMENTED = {
  Fault: {
    Code: {
      Value: "soap:client"
    },
    Reason: {
      Text: "Method not implemented"
    }
  }
};
var exports = module.exports = {};

exports.EventService = {
  EventService: {
    EventPort: {
      //var GetServiceCapabilities = { };
      GetServiceCapabilities: function (args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
      },
      //var CreatePullPointSubscription = { };
      CreatePullPointSubscription: function (args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
      }
    },
    PullPointSubscription: {
      //var PullMessages = { };
      PullMessages: function (args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
      },
      //var SetSynchronizationPoint = { };
      SetSynchronizationPoint: function (args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
      },
      //var Unsubscribe = { };
      Unsubscribe: function (args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
      }
    },
    SubscriptionManager: {
      //var Renew = { };
      Renew: function (args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
      },
      //var Unsubscribe = { };
      Unsubscribe: function (args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
      }
    },
    NotificationProducer: {
      //var Subscribe = { };
      Subscribe: function (args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
      }
    }
  }
};
