// This file is generated by the 'node-soap-servicegenerator'
// visit : https://github.com/BreeeZe/node-soap-servicegenerator for more info

var NOT_IMPLEMENTED = {
  Fault: {
    Code: {
      Value: "soap:client"
    },
    Reason: {
      Text: "Method not implemented"
    }
  }
};
var exports = module.exports = {};

exports.EventService = {
  EventService: {
    EventPort: {
      CreatePullPointSubscription: function(args /*, cb, headers*/ ) {
        throw NOT_IMPLEMENTED;
      },
      PullMessages: function(args /*, cb, headers*/ ) {
        throw NOT_IMPLEMENTED;
      },
      Seek: function(args /*, cb, headers*/ ) {
        throw NOT_IMPLEMENTED;
      },
      SetSynchronizationPoint: function(args /*, cb, headers*/ ) {
        throw NOT_IMPLEMENTED;
      },
      Unsubscribe: function(args /*, cb, headers*/ ) {
        throw NOT_IMPLEMENTED;
      }
    }
  }
};
